# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'MelodySampling' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MelodySampling

pod 'Firebase/Auth'
pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'Firebase/Crash'
pod 'Alamofire'
pod 'SwifterSwift'
pod 'IQKeyboardManagerSwift'
pod 'UICircularProgressRing'
pod 'SwiftyJSON'
pod 'Fabric'
pod 'Crashlytics'

end
