# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'King of Song Quiz' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for King of Song Quiz

pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'Firebase/Crash'
pod 'Firebase/Messaging'
pod 'Firebase/RemoteConfig'
pod 'Alamofire'
pod 'SwiftyJSON'
pod 'Fabric'
pod 'Crashlytics'
pod 'UICircularProgressRing'
pod 'IQKeyboardManagerSwift'


end
